# Generated by Django 4.2.7 on 2026-03-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_address_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1, help_text='Number of hours requested'),
        ),
    ]
