# Generated by Django 6.0.1 on 2026-02-20 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('default_negative_limit', models.DecimalField(decimal_places=2, default=-5000.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('screenshot', models.ImageField(upload_to='payment_proofs/')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_completed_orders_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_collected_from_customers', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_transferred_to_platform', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('negative_limit_threshold', models.DecimalField(decimal_places=2, default=-5000.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(limit_choices_to={'role': 'SERVICE_PROVIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ORDER_COMPLETED', 'Order Completed'), ('COMMISSION_DEDUCTED', 'Commission Deducted'), ('MANUAL_PAYMENT', 'Manual Payment'), ('ADJUSTMENT', 'Adjustment')], max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallets.providerwallet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_orders', models.IntegerField()),
                ('total_order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_collected_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='settlements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
