# Generated by Django 4.2.7 on 2026-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction_type',
            field=models.CharField(choices=[('ORDER_COMPLETED', 'Order Completed'), ('COMMISSION_DEDUCTED', 'Commission Deducted'), ('CASH_COLLECTED', 'Cash Collected'), ('MANUAL_PAYMENT', 'Manual Payment'), ('ADJUSTMENT', 'Adjustment')], max_length=50),
        ),
    ]
