# Generated by Django 4.2.7 on 2026-03-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_ledgerentry_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerwallet',
            old_name='current_balance',
            new_name='commission_balance',
        ),
        migrations.RenameField(
            model_name='providerwallet',
            old_name='platform_commission',
            new_name='total_commission',
        ),
        migrations.RenameField(
            model_name='providerwallet',
            old_name='provider_earnings',
            new_name='total_earning',
        ),
        migrations.RemoveField(
            model_name='providerwallet',
            name='total_completed_orders_amount',
        ),
        migrations.AddField(
            model_name='providerwallet',
            name='is_manually_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='default_negative_limit',
            field=models.DecimalField(decimal_places=2, default=-10000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='providerwallet',
            name='negative_limit_threshold',
            field=models.DecimalField(decimal_places=2, default=-10000.0, max_digits=12),
        ),
    ]
